ci: Disable coverage report submission.
The submission was failing too often.

Example of error (copied from [1]):

  ==> Detecting CI provider
      AppVeyor Detected
  ==> Preparing upload
  XX> Skip processing gcov
  ==> Collecting reports
  XX> Searching for reports disabled
      Targeting specific files
      + ./tests/coverage.xml bytes=2554
  ==> Uploading
      .url https://codecov.io
      .query commit=79753d5265adb936b092c393f6f722f23832d822&branch=master&job=scikit-build%2Fninja-python-distributions%2F0.0.1.153&service=appveyor&build=idmult5oyjeu7eu0&slug=scikit-build%2Fninja-python-distributions&package=py2.1.9
      Gzipping contents..
      Compressed contents to 934 bytes
      Pinging Codecov...
  Error: HTTPSConnectionPool(host='codecov.io', port=443): Max retries exceeded with url: /upload/v4?commit=79753d5265adb936b092c393f6f722f23832d822&branch=master&job=scikit-build%2Fninja-python-distributions%2F0.0.1.153&service=appveyor&build=idmult5oyjeu7eu0&slug=scikit-build%2Fninja-python-distributions&package=py2.1.9 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001245C2A5088>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
  Tip: See all example repositories: https://github.com/codecov?query=example
  A command failed while executing AFTER_TEST step.
    Return code:
      1
    Command:
      codecov -X gcov --required --file ./tests/coverage.xml
    Working directory:
      C:\projects\ninja-python-distributions
  Please see above for more information.
  Command exited with code 1

[1] https://ci.appveyor.com/project/scikit-build/ninja-python-distributions/builds/35130450/job/idmult5oyjeu7eu0